openapi: "3.0.2"
info:
  title: fitCloud
  version: "1.0"
servers:
  - url: https://aws-dev.fitcloud.co.kr
paths:
  /get_usage:
    get:
      summary: calculate aws resource usage per account in us dollar.
      description: calculate resource usage per account. The period could be one month, or it could be several months. Usage is expressed in dollars.
      operationId: get_usage
      parameters:
        - name: start_month
          in: query
          description: the start month of the period
          required: true
          schema:
            type: string
            example: "202309"
        - name: end_month
          in: query
          description: the end month of the period
          required: true
          schema:
            type: string
            example: "202309"

      responses:
        "200":
          description: Successful response containing the resource usage information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_sum:
                    type: string
                    description: aws resource usage amount in specific period in us dollar
